### ISSUE TITLE
Build Failed on Openshift CRC 4.10

### ISSUE THREAD

**Issue by javed-asif** [nodeshift-starters/devfile-sample#10]
I installed CRC 4.10 on Windows 10 and tried to create this application. Got followinf error:

npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm notice
npm notice New minor version of npm available! 8.3.1 -> 8.15.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.15.0>
npm notice Run `npm install -g npm@8.15.0` to update!
npm notice
npm ERR! code EACCES
npm ERR! syscall open
npm ERR! path /opt/app-root/src/package-lock.json
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, open '/opt/app-root/src/package-lock.json'
npm ERR! [Error: EACCES: permission denied, open '/opt/app-root/src/package-lock.json'] {
npm ERR! errno: -13,
npm ERR! code: 'EACCES',
npm ERR! syscall: 'open',
npm ERR! path: '/opt/app-root/src/package-lock.json'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.
npm ERR! A complete log of this run can be found in:
npm ERR! /opt/app-root/src/.npm/_logs/2022-07-26T22_36_23_468Z-debug-0.log
[2/2] STEP 1/8: FROM registry.access.redhat.com/ubi8/nodejs-16-minimal:latest
[2/2] STEP 2/8: COPY --from=0 /opt/app-root/src/node_modules /opt/app-root/src/node_modules
Error shutting down storage: A layer is mounted: layer is in use by a container
error: build error: error building at STEP "RUN npm install --production": error while running runtime: exit status 243

**Comment by helio-frota** [comment]
@javed-asif thanks for reporting this!

So I've added the bug label but the fact is that we are not 100% sure if that is something we should do in this repository or reporting on the ubi image itself. Because we @pacostas and @BethGriggs have tested with the version 14 and no problems found.

We have this PR merged https://github.com/nodeshift-starters/devfile-sample/pull/12 to use `npm ci` , can you please double check and try again when you have time?

Thanks

**Comment by helio-frota** [comment]
Closing this, feel free to reopen in case still not working.
